<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MacBook-Pro" failures="2" tests="3" name="invalidGet" time="0.506" errors="0" timestamp="2023-09-06T11:02:53 SGT">
  <testcase classname="Lab8_Practice.invalidGet" name="TC08_StatusCodeChecked" time="0.003"/>
  <testcase classname="Lab8_Practice.invalidGet" name="TC09_MessageChecked" time="0.002">
    <failure type="java.lang.AssertionError" message="Message field check Failed! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Message field check Failed! expected [true] but found [false]
at Lab8_Practice.invalidGet.TC09_MessageChecked(invalidGet.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- TC09_MessageChecked -->
  <testcase classname="Lab8_Practice.invalidGet" name="TC10_verifyOnContentOfMessage" time="0.013">
    <failure type="java.lang.AssertionError" message="Content of message shows incorrect! expected [User not found!] but found [null]">
      <![CDATA[java.lang.AssertionError: Content of message shows incorrect! expected [User not found!] but found [null]
at Lab8_Practice.invalidGet.TC10_verifyOnContentOfMessage(invalidGet.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- TC10_verifyOnContentOfMessage -->
</testsuite> <!-- invalidGet -->
